root = "."
tmp_dir = "tmp"

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "go build -o /app/tmp/mebook -v cmd/main.go"
bin = "/app/tmp/mebook"

# Customize binary.
full_bin = "/app/tmp/mebook"

# This log file places in your tmp_dir.
log = "air_errors.log"
include_ext = ["go", "yml"]
exclude_dir = ["tmp"]
delay = 1000 # ms

[log]
time = true

[misc]
clean_on_exit = true