FROM golang:1.16.7-buster
ARG AIR_VERSION=1.27.3

WORKDIR /go/bin

RUN curl -s -L https://github.com/cosmtrek/air/releases/download/v${AIR_VERSION}/air_${AIR_VERSION}_linux_amd64 > air_${AIR_VERSION}_linux_amd64 && \
    mv air_${AIR_VERSION}_linux_amd64 air && \
    chmod +x /go/bin/air && rm -rf *.txt

WORKDIR /app
CMD ["air", "-c", "air.toml"]