name: Tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Install and set Flutter version
        uses: subosito/flutter-action@v1.5.3
        with:
          flutter-version: '2.5.3'
      - name: Restore packages
        run: |
            cd mobile
            echo "NEWS_API_KEY=${{ secrets.NEWS_API_KEY }}" > .env
            flutter pub get
      - name: Add file to indicate dart files to codecov
        run: |
            cd mobile
            file=test/coverage_helper_test.dart
            echo "// Helper file to make coverage work for all dart files\n" > $file
            echo "// ignore_for_file: unused_import" >> $file
            find lib '!' -path '*generated*/*' '!' -name '*.g.dart' '!' -name '*.part.dart' '!' -name '*.freezed.dart' -name '*.dart' | cut -c4- | awk -v package=$1 '{printf "import '\''package:mebook%s%s'\'';\n", package, $1}'
            echo "void main(){}" >> $file
            cat $file
      - name: Run tests
        run: |
            cd mobile
            flutter test --coverage
      - name: Install lcov
        run: sudo apt-get install -y lcov
      - name: Remove generated files from code coverage report
        run: lcov --remove mobile/coverage/lcov.info 'lib/*/*.freezed.dart' 'lib/*/*.g.dart' 'lib/*/*.part.dart' 'lib/generated/*.dart' 'lib/generated/*/*.dart' -o mobile/coverage/lcov.info
      - name: Upload coverage to codecov
        run: |
            curl -Os https://uploader.codecov.io/v0.1.0_4653/linux/codecov
            chmod +x codecov
            ./codecov -t ${{ secrets.CODECOV_TOKEN }} -f mobile/coverage/lcov.info -Z
        shell: bash
